### ISSUE TITLE
Videos

### ISSUE THREAD

**Issue by Syreyup** [marcomaroni-github/twitter-to-bluesky#7] opened 2024-10-19 02:23 UTC
Videos are now supported on bluesky. does this work/any plans for this to work now? the description says not but it could just be out of date. I would like to make sure before i go through with it.

**Comment by marcomaroni-github** [comment] 2024-10-19 07:34
Yes it is in the plans but I am waiting for the official SDK documentation.

**Comment by marcomaroni-github** [comment] 2024-10-20 09:12
It seems that the team has published some [examples](https://bsky.app/profile/samuel.bsky.team/post/3l6supolf6w25), ​​but it does not seem trivial and above all I have to verify that this method is applicable within a batch import process. I will look into it in the next few days.

**Comment by marcomaroni-github** [comment] 2024-10-20 10:42
@Syreyup I implemented a first version, I didn't do many tests because I have very few videos in my archive, if you want to try the code is in the branch https://github.com/marcomaroni-github/twitter-to-bluesky/tree/video-support

**Comment by Syreyup** [comment] 2024-10-20 19:31
ill test this later on my twitter account and a throwaway bluesky account, thanks!

**Comment by Syreyup** [comment] 2024-10-21 03:57
Archive request sent to Twitter, will update later

**Comment by Lucifer-is-my-pet** [comment] 2024-10-21 21:50
I've tried it with one of my tweets and got "Local video file not found into archive, tweet discarded" message so the tweet was imported without video. `baseVideoPath` was not full.
`const baseVideoPath = `${process.env.ARCHIVE_FOLDER}/data/tweets_media/${tweet.id}-`;`
there should be the second part of the filename which I found inside `media.video_info.variants` array, inside the url of the element with the highest (largest?) bitrate

**Comment by marcomaroni-github** [comment] 2024-10-22 06:42
@Lucifer-is-my-pet I pushed a change that allows you to see the local path you searched for. Try relaunching and checking.

**Comment by Lucifer-is-my-pet** [comment] 2024-10-22 11:40
oof, I was mistaken 🤦  apparently the error was caused by the url tail `?tag=10`. cutting it off helped to get the correct file path but the imported tweet still has no embedded video... looking into it.

**Comment by Lucifer-is-my-pet** [comment] 2024-10-22 16:22
so... first of all, as I see in logs the video was uploaded the first time I tried to import that tweet 
```
 Updaload video
 JobId: csboq8cqkvks715osfu0
  Status: JOB_STATE_CREATED
  Status: JOB_STATE_ENCODING 81
  Status: JOB_STATE_ENCODING 2
  Status: JOB_STATE_ENCODING 26
  Status: JOB_STATE_ENCODING 51
  Status: JOB_STATE_ENCODING 99
  Status: JOB_STATE_SCANNING
  Status: JOB_STATE_SCANNING
  Status: JOB_STATE_SCANNED
  Status: JOB_STATE_SCANNED
  Status: JOB_STATE_COMPLETED
```
every other attempt only got me this message:
```
JobId: csboq8cqkvks715osfu0
  Status: JOB_STATE_COMPLETED
```
the `postRecord` with video looks like this:
```
{
  '$type': 'app.bsky.feed.post',
  text: 'Февральское видео, снятое папой ',
  facets: undefined,
  createdAt: '2020-09-15T20:23:13.000Z',
  embed: undefined
}
```
`uploadUrl` = `https://video.bsky.app/xrpc/app.bsky.video.uploadVideo?did=did%3Aplc%3Ajioqe5ky2c2zclwogfrhxiws&name=1305965417182228480-RHb4tmSa_kRUow06.mp4`
not sure if it's of any use
`status.jobStatus` looks like this:
```
{
  blob: BlobRef {
    ref: CID(bafkreiebwwaulobh4yossoklnfpqu6gfy3m4pdhw2tf2m3equm4xzo2z3u),
    mimeType: 'video/mp4',
    size: 1972160,
    original: {
      '$type': 'blob',
      ref: CID(bafkreiebwwaulobh4yossoklnfpqu6gfy3m4pdhw2tf2m3equm4xzo2z3u),
      mimeType: 'video/mp4',
      size: 1972160
    }
  },
  did: 'did:plc:jioqe5ky2c2zclwogfrhxiws',
  jobId: 'csboq8cqkvks715osfu0',
  message: 'Video processed successfully',
  state: 'JOB_STATE_COMPLETED'
}
```
not sure what to make of it .__.

**Comment by Lucifer-is-my-pet** [comment] 2024-10-22 21:53
[proposed some fixes](https://github.com/marcomaroni-github/twitter-to-bluesky/compare/video-support...Lucifer-is-my-pet:twitter-to-bluesky:patch-1)

**Comment by marcomaroni-github** [comment] 2024-10-23 06:09
@Lucifer-is-my-pet I fixed in case tailIndex is -1, otherwise the file name was not formed correctly

**Comment by marcomaroni-github** [comment] 2024-10-30 09:23
@wicogohome I merged the last version of the main branch to this new video branch, can you please help me to verify if it'all is correct?  In particular in the function getMergeEmbed

Thanks.

**Comment by wicogohome** [comment] 2024-10-31 05:01
> @wicogohome I merged the last version of the main branch to this new [video branch](https://github.com/marcomaroni-github/twitter-to-bluesky/tree/video-support), can you please help me to verify if it'all is correct? In particular in the function getMergeEmbed
> 
> Thanks.

Hi @marcomaroni-github,I reviewed the code and tested the embedded image/record.   
It still works fine.   
But I don't have any videos on Twitter, so I can't test the video type.

There are some of my recommendations:

1. Line 313 ~ 315, 319 ~ 322 are duplicated.
```ts
// app.ts
 if (jobStatus.error) {
       console.warn(`${jobStatus.error}. Video will be posted as link`);
       continue;
}
```

2. Maybe the `embeddedVideo` could just be a blob, and we could set the `$type` in `getMergeEmbed()` to unify the formatting like records and pictures.

**Comment by marcomaroni-github** [comment] 2024-10-31 09:34
Thanks @wicogohome , fixed both points, also that video check was uselessly discarding the tweet import in case of video already imported.

I would say we can go into beta with this branch.

**Comment by marcomaroni-github** [comment] 2024-11-06 07:19
Merged with the main branch and officially added video support

**Closed by marcomaroni-github** 2024-11-06 07:19 UTC
Labels: enhancement
